### ISSUE TITLE
Page 22 - Title Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#100]
In the entry for Non-Human Person (NHP) on page 22, the title of the book (No Room For a Wallflower) appears without being italicized as it is when mentioned elsewhere in the text. For consistency with other uses, the mention of the title in this entry should be italicized.

**Comment by Piezoelectric** [comment]
The text now reads

> While the Egregorians could also be considered NHPs, *No Room For A Wallflower* uses the term only for these “Deimosian” NHPs.

Italics have been included
