### ISSUE TITLE
Page 176 - Title Formatting Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#101]
In this section on page 176:

"If your Egregorian character goes offworld and continues their adventures elsewhere in the galaxy after concluding this arc of **No Room For A Wallflower**"

the title of the book is not italicized as per other uses throughout the text, and for consistency should be.

**Comment by Piezoelectric** [comment]
The text mentioned has been italicized
