### ISSUE TITLE
Page 193 - Strider Skirmisher Kit Designer Clarification

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#102]
The Strider's Skirmisher Kit swap bonus reads "This turn only, the Strider becomes INVISIBLE and their movement ignores difficult terrain and engagement, and does not provoke reactions."

The question has arisen, which I am also curious about, as to what the purpose of the Invisibility in this is. It only lasts for that turn before vanishing, which means that it doesn't support hiding very well as it will break, and the defensive bonus of being Invisible is superseded by the fact that the Strider during this same period does not provoke reactions at all, meaning that the Invisibility versus reaction attacks wouldn't even come into play.

I'd like to consult with Tom about this to get his take on things and to see if there's perhaps something that I'm missing as to the purpose this serves. If it turns out to be redundant with the other components of the kit, then I think this swap bonus could potentially be streamlined by removing the Invisibility component, i.e. ""This turn only, the Strider's movement ignores difficult terrain and engagement, and does not provoke reactions."

**Comment by Piezoelectric** [comment]
The invisiblity text has been removed, and the swap bonus now reads "This turn only, the Strider's movement ignors difficult terrain and engagement, and does not provoke reactions"
