### ISSUE TITLE
Page 3 - Illustrator Name Typo

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#103]
In the illustration credits, "Dan Morrison" is named. If this is the artist I'm thinking of, his name is actually "Dan Morison" with only one R.

**Comment by KaiTave** [comment]
There's another typo as well: Hannah Templer's name is spelled "Hannah Templar."

**Comment by Piezoelectric** [comment]
Both names are corrected in 2021-05-17
