### ISSUE TITLE
Page 55 - [The Broadcast]'s Terrordome has Recharge 5+

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#106]
The system is otherwise identical to the Spite's Seize - if this intentional, disregard, obviously :)

**Comment by KaiTave** [comment]
More specifically, the discrepancy is that based off the Spite's own Seize, the Recharge should be 4+, not 5+, to be consistent with the base NPC class it derives from.

**Comment by Piezoelectric** [comment]
Amended to recharge 4+
