### ISSUE TITLE
Pages 190-193 - NPC To-Hit Info Formatting Discrepancy/Clarification, and Strider Weapons Missing To-Hit Info

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#109]
In Lancer's core rulebook, NPC to-hit info is not listed as "vs Evasion" as the default assumption is that unless an attack is a tech attack or has the Smart tag, it will target Evasion by default. The Wallflower NPCs therefore technically have redundant information in many of their statblocks that could be deleted to line up closer with the statblock formatting of the core rulebook. From pages 190-193, the following statblocks have unnecessary labeling of "vs Evasion" in them:

-Slug Pistol
-Judgement Shotgun
-Scouring Whip
-Ripper Claws
-Shoulder Mortar
-Mag Shotgun

This is not necessarily a grievous error in need of correction as the to-hit information is all technically correct, but the question is whether exact parity with the corebook's formatting is desired, or if the desire is for Wallflower's version to take precedence in this case.

An additional discrepancy in either case, the Strider NPC's Ranger Long Rifle and Explosive Rifle are missing to-hit info from the statblocks. Both of these should say +0 (or +0 vs Evasion if this is the style being employed) as well as +1 Accuracy, to line up with other examples of attacks with +0 to hit such as the Lurker's Scouring Whip and Ripper Claws.

**Comment by Piezoelectric** [comment]
"to Evasion" has been removed from weapon statblocks, example below:

![image](https://user-images.githubusercontent.com/23746623/118532104-31ec6a80-b70c-11eb-8efe-2fe1554af741.png)

Ranger Long Rifle now declares +0, +1 accuracy

Explosive Rifle declares the same
