### ISSUE TITLE
Page 143 - Possible word choice issue? - kilos for kilometers

### ISSUE THREAD

**Issue by junbl** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#110]
In the fourth paragraph, a human scout says "ten kilos from evergreen." I assume this is intended to mean kilometers, but I've only ever heard kilos to mean kilograms. Maybe "ten clicks" as a possible replacement?

Obviously it's 15000 years in the future so the assumption that the spoken language, let alone military slang, matches ours is just a convenience. But either way, it's confusing using current day slang that refers to something different.

**Comment by KaiTave** [comment]
I feel it should be noted here that if that particular shorthand for kilometers is used, it's spelled "klicks" instead of "clicks."

**Comment by Piezoelectric** [comment]
now reads  "ten klicks from Evergreen"
