### ISSUE TITLE
Page 190 - Avenger Statblock Bolding Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#111]
The Avenger's Assault Armor states the following, with this bolding: "The Avenger has **RESISTANCE to all damage originating within RANGE 3."** 

Per other examples of similar abilities found in the core rulebook, the formatting for this should only bold the keyword RESISTANCE, for example:  "The Avenger has **RESISTANCE** to all damage originating within RANGE 3."

**Comment by Piezoelectric** [comment]
bolding was fixed
