### ISSUE TITLE
Page 188 - Guerrilla Warfare Burst/Blast Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#112]
The Ranger Swallowtail's Guerrilla Warfare core power uses Burst iconography for its smoke patches. While this is in line with the language that was used in prior drafts of Wallflower, the term those drafts used was likely incorrect as the smoke patches are not centered on a particular object or actor. Similar to this ticket https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/65 I would suggest that Blast iconography would be more appropriate here, similar to the smoke grenades from the core rulebook.

**Comment by Piezoelectric** [comment]
Now uses blasts
