### ISSUE TITLE
Page 69 - Regret Statblock Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#116]
The HASE stats for Regret on the top of page 69 list its Engineering as +2, while the Berserker NPC class it's based on has an Engineering of -1. Is this meant to be a deliberate change or no? Consultation with Tom may be necessary to determine if this is intentional, but if it isn't then Regret's Engineering should be changed to fall in line with that of the NPC class in order to avoid confusion and maintain consistency.

**Comment by Piezoelectric** [comment]
Amended to -1
