### ISSUE TITLE
Page 209 - Synchronous Layer Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#12]
Horrible Realization states "This weapon doesn’t suffer from engagement penalties" but this is an inherent quality of all Memetic type weapons anyway as noted on page 199. This seems like a holdover perhaps from an earlier version where the Mimetic weapon concept wasn't fully in place yet. Given this redundancy, I think this part of Horrible Realization can safely be deleted.

**Comment by Piezoelectric** [comment]
The text of Horrible Realization doesn't include engagement now
