### ISSUE TITLE
Page 180 - PEBCAC Statblock Color Formatting Error

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#120]
The Kidd's PEBCAC is a Quick Tech granting system, and therefore it should use the same purple color and Tech Action header iconography as, for example, the Field-Approved, Brass-Ignorant Modifications on the same page.

**Comment by Piezoelectric** [comment]
Duplicate of https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/4
