### ISSUE TITLE
Page 157 - Possible word missing - schedule _ printer

### ISSUE THREAD

**Issue by junbl** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#123]
In the first paragraph of "Going to Quiet Night", the book mentions a "dormant schedule printer". In other places, e.g. the description of the printer in Evergreen, it has "Schedule 2 facility" (p 37), or in the core book as a "schedule X printer" (p 377). I do see a reference to an unspecified "scheduled [printer]"  on p 39, but that's said to be S2 in other places. 

Not clear if something's missing or if it's intentionally unspecified.

**Comment by Piezoelectric** [comment]
Wording has been amended to "a dormant printer". The size is unspecified, which could be read as intentional.
