### ISSUE TITLE
Pages 54, 166 - Subaltern Area Discrepancies

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#127]
In several encounters, The Horde and Fire Walk With Me, there are terrain hazards in play representing swarms of subalterns which act as dangerous terrain and can be destroyed by dealing damage to them. However, the rules for doing this are somewhat different each time. In The Horde, we have the following:

"The areas marked on the map as dangerous and difficult terrain represent the large swarms of subalterns clambering onto or damaging mechs. These zones of subalterns can be cleared by dealing 10 damage to them; attacks against them always hit."

In Fire Walk With Me, we have the following:

"Large groups of subalterns mill around the compound, represented on the battlefield as areas of dangerous terrain. This dangerous terrain deals KINETIC. These can be dispersed by dealing 5 damage or 5 HEAT to them. Any attacks against them automatically hit."

In addition to this, neither of these sections states what type of damage this dangerous terrain does, whereas another combat encounter where swarms of subalterns (these ones apparently untargetable) are present, High Water on page 165, does mention that:

"They count as dangerous terrain for characters entering them for the first time in a turn or starting a turn in them. Characters caught in this way must succeed on a HULL save or take 5 KINETIC."

In addition to these discrepancies, I would like to note that per the core rulebook, the rules for Dangerous Terrain call for Engineering saves, not Hull saves. Is this an intentional change, or should the Hull save on page 165 be changed and brought in line with the core rulebook?

***

I would like to suggest that for clarity and consistency that these two encounters on page 54 and 166 be brought into line with one another, unless there's a compelling reason to have them differentiated in this way. One of them takes 10 damage, one takes 5. One is both difficult and dangerous terrain, one is only dangerous terrain. At the very least, my recommendation is to have the encounter in The Horde follow the damage rules used in Fire Walk With Me, and for both sections to include info on the damage type they deal.

For The Horde (page 54), therefore, I would suggest:

"The areas marked on the map as dangerous and difficult terrain represent the large swarms of subalterns clambering onto or damaging mechs. This dangerous terrain deals KINETIC. These zones of subalterns can be cleared by dealing 5 damage or 5 HEAT to them; attacks against them always hit."

And for Fire Walk With Me (page 166), I would suggest:

"Large groups of subalterns mill around the compound, represented on the battlefield as areas of dangerous terrain. This dangerous terrain deals KINETIC. These can be dispersed by dealing 5 damage or 5 HEAT to them. Any attacks against them automatically hit."

Then I would confer with Tom to determine if A). the areas in Fire Walk With Me should count as both difficult _and_ dangerous terrain, and B). if the save noted on page 165 should be HULL or ENGINEERING. If it's meant to be HULL, then the descriptions of the areas on page 54 and 166 should also note this, as it's different from the core rulebook's definition of how dangerous terrain functions.

**Comment by Piezoelectric** [comment]
The Horde's subalterns are currently
* dangerous/difficult terrain
* 5 kinetic on failed hull save (previously unspecified)
* dispersed wtih either 5 damage or 5 heat (previously 10 damage)
* always hit by attacks

Fire Walk With Me's subalterns are currently:
* difficult and dangerous
* 5 kinetic on failed hull save
* dispersed on 5 damage or 5 heat, auto hit

"Should this be a hull or engineering save" has not been explicitly addressed; up to @KaiTave if they consider this sufficient acknowledgment.

**Comment by KaiTave** [comment]
As long as they're both consistent, which they seem to be, it looks good to me. Closed.
