### ISSUE TITLE
Page 184 - Potential Enkidu Adjustments

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#131]
As Tom has stated that a pass on Wallflower may be happening soon, this ticket is here as a note to confer with Tom regarding possible adjustments to the Enkidu alt-frame. After Wallflower's release, it was noted that the Enkidu had undergone some last minute changes to its design, such as losing the Heavy mount it had previously.

Tom mentioned that after further playtesting he might consider making adjustments to the Enkidu's stats, such as granting it armor. There has since been a number of playtests and feedback which have been pinned in the New Release Feedback channel regarding the present Enkidu and its performance, many of which have suggested other possible adjustments such as additional repair cap.

None of this is confirmed errata, but if Wallflower is going to be given an additional editing/errata pass then that would probably be the ideal time to confer with Tom on this matter if he wishes to make any such adjustments so they can all be incorporated at once.

**Comment by Piezoelectric** [comment]
If Tom is adjusting the Enkidu, he may also wish to adjust the verbiage on Bifurcate. See https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/104

**Comment by KaiTave** [comment]
This is now a more formal errata with a number of changes.

![image](https://user-images.githubusercontent.com/46460730/116830149-f32bb180-ab5c-11eb-9660-b4aa987804e9.png)

**Comment by Piezoelectric** [comment]
Formally addressed in the 2021-05-17 release; changes are documented in https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/154.
