### ISSUE TITLE
Page 203 - Labyrinthine Layer Clarification

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#133]
The Labyrinthine Layer's INCORRECT ability states "1-2 characters within SENSORS, or a character that **lost a contested check** take 3/4/5 HEAT and are knocked back 4 spaces in a direction of the Eidolon’s choice."

This layer doesn't prompt checks, but instead forces a sort of guessing memory game. As stated in its rules, "For each incorrect guess, the Eidolon uses INCORRECT against them as a reaction, ignoring the 1/turn limit." Therefore, instead of "lost a contested check" in the wording for INCORRECT, it would probably be clearer to word it in the following way instead:

"1-2 characters within SENSORS, or a character that **made an incorrect guess,** take 3/4/5 HEAT and are knocked back 4 spaces in a direction of the Eidolon’s choice."

**Comment by Piezoelectric** [comment]
Verbiage as of 2021-05-17 reads "1-2 characters within Sensors, or a character that **guessed incorrectly**"
