### ISSUE TITLE
Page 66 - Reactor Defense Almost Impossible To Lose

### ISSUE THREAD

**Issue by Arcranmon** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#134]
As-written, the Reactor Defense combat is almost impossible for the players to lose, even if they completely ignore the Demolisher. With 40 HP, it will take the Demolisher four attacks to destroy the Power Regulator. As the fight only has five rounds, unless the Demolisher starts within 4 of the Power Regulator,  there's a very low chance that it can actually destroy the Regulator in the given time frame (only a ~15% chance to hit four consecutive attacks against Evasion 5.)

The Power Regulator had 30 HP in a previous draft, which makes this a bit more challenging, but it might need a little more juice on the enemy side.

**Comment by Piezoelectric** [comment]
The objective now is Size 2, Eva 5, and has 20HP. A T1 demolisher can destroy that in 2 hits (assuming it *does* hit).
