### ISSUE TITLE
Page 152 - Accumulation Turn Count Discrepancy

### ISSUE THREAD

**Issue by lenaleciel** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#135]
In the "As an Ultra" box, the Accumulation is described as taking 2 turns, or 3 turns if "there are 4 or more players."

Usually, Ultras get their extra turn (for a total of 3) if there are 5 or more hostile characters, as described in the core book.

Please check with Tom to see if this is a typo (in which case it should be changed to 5 or more) or if this is an intentional change (in which case the difference from usual Ultras should be pointed out. It is most likely just a typo though.

**Comment by Piezoelectric** [comment]
It was a typo; the current wording is

> AS AN ULTRA, [THE ACCUMULATION]:
> Takes two separate turns each round, or three if there are 5 or more players
