### ISSUE TITLE
page 11 typo

### ISSUE THREAD

**Issue by ToodlePeep** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#14]
![image](https://user-images.githubusercontent.com/80489106/110857366-b1932e80-82b0-11eb-8e72-c3a71aa12d8d.png)

this should presumably say can **and** will.

Attrition is always a factor in Lancer. PCs should
generally face two or three fights between each FULL
REPAIR. PCs become much more powerful if they only
have to go through one fight per FULL REPAIR, since
they **can will** have immediate access to their CORE
POWER, repairs, and plenty of charges for their LIMITED
systems. No Room For A Wallflower is designed with
the standard pacing in mind; if you deviate from it,
you will need to keep this in mind.

**Comment by Piezoelectric** [comment]
Text now reads

> "PCs become much more powerful if they only have to go through one fight per FULL REPAIR, since **they will** have immediate access to their CORE POWER"
