### ISSUE TITLE
Page 204 - Punishment Layer Discipline Typo

### ISSUE THREAD

**Issue by InterpointRalf** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#140]
The "Discipline" ability of the Punishment layer speaks of clearing the Exposed _Condition_ when it is a Status.

**Comment by Piezoelectric** [comment]
![image](https://user-images.githubusercontent.com/23746623/118526261-ad96e900-b705-11eb-8f62-6d34006eca85.png)


Fixed in 2021-05-17
