### ISSUE TITLE
Page 206 - Share Pain Confusing Timing / Action Cost / Duration

### ISSUE THREAD

**Issue by InterpointRalf** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#141]
Share Pain is a Quick Action that the Eidolon as per Predictable has to take on its turn. 

The line "The Eidolon must choose a new target for this effect at the start of each of its turns." is confusing since it is unclear whether it takes the action again or if it just chooses a new target for the effect of the previous action. 

Additionally the ability has no duration and no limit on how often it can affect characters, leading to Share Pain eventually affecting all players while awkwardly having to swap the effect of each taken Quick Action to a different target.

I guess it boils down to the following:

1. The Ability needs a Duration.

2. The line:

"The Eidolon must choose a new target for this
effect at the start of each of its turns."

Should probably read

"The Eidolon must take this Quick Action at the start of its turn (following the normal restrictions on action economy) and can't target the same character two turns in a row."

Or something similar, instead of merely redirecting the _effect_ of an indefinite Quick Action that it also has to take again on its turn due to predictable.

**Comment by KaiTave** [comment]
The hints for this layer states "One character is linked to the Eidolon at a time" which suggests the intent is that each turn the Eidolon uses Share Pain on a different target, transferring the effect. If that is the intent then the simplest way I can think to clarify that is to simply state within the ability description, adding on to the second sentence in the rules block, for example "This ability can only affect a single character at a time, and the Eidolon must choose a new target for this ability at the start of each of its turns."

**Comment by InterpointRalf** [comment]
I think incorporating the Action Cost of 1 Quick Action is important instead of just "choosing a new target for this effect" which on the face of it doesn't equate to the Eidolon taking the Quick Action again.

I think 

"This ability can only affect a single character at a time, and the Eidolon must use this Quick Action on a different target at the start of each of its turns."

Would cover it.

**Comment by Piezoelectric** [comment]
> "This ability can only affect a single character at a time, and the Eidolon must use this Quick Action on a different target at the start of each of its turns."

Ralf's wording was incorporated into the text as of 2021-05-17
