### ISSUE TITLE
Page 206 - Splintering tendrils Immobilized Bonus Damage 

### ISSUE THREAD

**Issue by InterpointRalf** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#142]
The Canopy Layer's Splintering Tendrils have the Punishment Layer Release weapon special rules attached.

**Comment by KaiTave** [comment]
Specifically, the Canopy layer's Splintering Tendrils reads "This weapon can attack two targets within line of sight
at a time. It deals +3 KINETIC to IMMOBILIZED characters." This appears to be transposed rules text from the Punishment layer's Release ability. Earlier drafts simply had Splintering Tendrils dealing its attack damage without any special rules text. As such it can be deleted from Splintering Tendrils.

![splintering](https://user-images.githubusercontent.com/46460730/114366390-4303f380-9b30-11eb-88f1-a1e61e34dfc7.jpg)

**Comment by Piezoelectric** [comment]
![image](https://user-images.githubusercontent.com/23746623/118525911-50029c80-b705-11eb-987a-4714913ca27c.png)

Fixed 2021-05-17
