### ISSUE TITLE
Page 208 - Tempest Hint Typo

### ISSUE THREAD

**Issue by InterpointRalf** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#143]
Hint of the Tempest layer reads "Bunch" when it should be "Bunching".

**Comment by Piezoelectric** [comment]
More specifically, the Hint currently reads "Bunch up against this layer may be a terrible idea...", and "Bunching up against this layer" is the correct phrase

**Comment by Piezoelectric** [comment]
![image](https://user-images.githubusercontent.com/23746623/118525520-e5e9f780-b704-11eb-8f41-9a06d17a45d2.png)

Fixed
