### ISSUE TITLE
Page 209 - Abyssal Layer Share line of sight but still can't target.

### ISSUE THREAD

**Issue by InterpointRalf** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#144]
"Hostile characters can't draw line of sight to or target anything further away than Range 2. However they do share line of sight with allied characters, allowing them to act as spotters for each other."

Can't draw LoS and can't target are listed as two distinct separate effects from each other. Allies giving you LoS doesn't give you the ability to target things within Range 2 to them RaW.

If this isn't intentional there would need to be another clause addressing the targeting.

**Comment by KaiTave** [comment]
Probably the simplest clarification for this would be something along the lines of "Hostile characters can't draw line of sight to or target anything further away than Range 2. However they do share line of sight with allied characters **and can make attacks against targets within range 2 of them**, allowing them to act as spotters for each other."

**Comment by Piezoelectric** [comment]
![image](https://user-images.githubusercontent.com/23746623/118525456-d074cd80-b704-11eb-825a-c4cae06c1d76.png)
