### ISSUE TITLE
Page 65 - Specter Optional Modules Clarification

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#145]
The Night Strike fight on page 65 lists for 5 PCs a Specter NPC with Sap and Step. Specters do not have access to the Sap ability by default. They _do_ have Drain Systems which is another tech action ability that stuns targets. Is the Specter in this encounter supposed to have a cross-classed ability from one of the other NPC classes, or is this an error and it should be Drain Systems instead?

**Comment by Piezoelectric** [comment]
![image](https://user-images.githubusercontent.com/23746623/118524919-462c6980-b704-11eb-91e8-10341aba4539.png)

Sap was replaced with Drain Systems.
