### ISSUE TITLE
Page 69 - Possible Size typo for REGRET

### ISSUE THREAD

**Issue by VexxMyst** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#146]
REGRET is listed as a Size 2 NPC, while both the Berserker NPC and the Enkidu frame it's made from is a Size 1. Disregard this if intentional.

**Comment by KaiTave** [comment]
The Enkidu is actually size 2 as listed on page 184, so as far as I can tell REGRET being size 2 is meant to be consistent with that.

**Comment by VexxMyst** [comment]
Oh, so it is! I could've sworn I looked at it in the PDF or on Comp/Con and it was listed as a size 1; It's also possible I imagined it would be the same size as a Tokugawa, my mistake.
