### ISSUE TITLE
Page 67-69 Regret Juggernaut Berserker System

### ISSUE THREAD

**Issue by lenaleciel** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#147]
Regret is listed as having Juggernaut and Superhot as the Berserker options on the Enemy Forces box on page 67, but it is not listed as an optional trait that Regret has on page 69.

Also double check that it is intentional that Regret has Juggernaut (Berserker optional trait) as there is a trait of Ultras by the same name with a different effect that is not listed by name in Regret's statblock, but the effect itself is there in the box that lists general abilities Ultras do have.

**Comment by KaiTave** [comment]
REGRET's Ultra optionals are Hellfire Projector and Unstoppable, so the Juggernaut listed in this case should be the Berserker optional. I believe its inclusion is intentional and it should probably be listed in the expanded statblocks on page 69.

**Comment by lenaleciel** [comment]
turns out the Juggernaut optional was already built into the Avalanche Charge description it modifies as an Optional System, this is fine.
