### ISSUE TITLE
Canopy Layer (Eidolon 13)

### ISSUE THREAD

**Issue by MayCauseAnnihilation** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#148]
On Page 206 the Canopy layer states that the only way it can take damage is from it's Shards Linked trait, but it has no such trait - the trait being referred to is called Disciplined. Old version artifact, I'm guessing.

**Comment by KaiTave** [comment]
A ticket already exists regarding this issue: https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/33

**Comment by Piezoelectric** [comment]
Closed as duplicate
