### ISSUE TITLE
Page 67-69 - Regret Encounter Errors

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#17]
"REGRET is the first ULTRA the PCs will fight. ULTRAS
are extremely powerful and get multiple turns each
round. During the battle, remind players about their
options, including BRACE , SCAN , and using multiple
avenues of attack. REGRET is fast **and very hard to
pin down due to its SUPERIOR FRAME "**

At one point Regret did have Superior Frame but that was changed out for Unstoppable. This sentence may need a minor rewrite, but at the very least it should say UNSTOPPABLE here instead of SUPERIOR FRAME, i.e. 

"and very hard to pin down due to UNSTOPPABLE"

Also on page 69, the statblock for Regret's Chain Axe has its damage listed as **3 kinetic** when it should be **7 kinetic** instead.

**Comment by lenaleciel** [comment]
Both of these issues were fixed in the May 17th release.
