### ISSUE TITLE
Page 64 - Beat 8 is labelled Beat 4

### ISSUE THREAD

**Issue by undacvr** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#2]

**Comment by Piezoelectric** [comment]
The typo is on page 63, the table of contents here: 

![image](https://user-images.githubusercontent.com/23746623/113429283-e40ae580-939d-11eb-90f5-69f2de11c88d.png)

**Comment by Piezoelectric** [comment]
Now refers to Beat 8: Elegy for the Dead
