### ISSUE TITLE
Pages 184, 186, 188 - Alt Frames Lack Size/Role Icons

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#20]
The Enkidu, Genghis Mk1, and Ranger Swallowtail all lack size and role icons in the upper corner of their main pages. It's possible this was a deliberate decision, but if not then for consistency they should likely have them added.

**Comment by Piezoelectric** [comment]
Size icons have been added
