### ISSUE TITLE
Page 199 - Memetic Weapons Attack Type Clarification

### ISSUE THREAD

**Issue by lenaleciel** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#23]
As a new weapon type, it's not inherently defined as to whether or not memetic weapons make Ranged Attacks or Melee attacks for the purpose of interacting with player systems that care about one type or the other. One can mostly guess based on whether the weapon has a Range value or a Threat value, but clarification would be appreciated, especially on weapons with templates like Burst 1.

**Comment by Piezoelectric** [comment]
Text now reads "These ranged weapons ignore engagement and do not affect allied characters".

Worth noting that Splintering Tendrils still has a Threat 1 icon. I suppose Threat 1 makes more sense than "Range 1". Horrible Realization also has a Threat 5 icon. Will create new issues for both.
