### ISSUE TITLE
Page 40 - Small Typo

### ISSUE THREAD

**Issue by eternalAffliction** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#26]
In the fifth paragraph in the right-hand column, the word after "settlement" has a typo, and ought to be "to".

**Comment by Piezoelectric** [comment]
Text now reads

> Evergreen operates on a hundred-year plan: a century after landfall, the colony will be at capacity – 200,000 citizens – and well on the way to a complete transition from an NHP-administered **settlement to one** governed by a fully organic leadership.
