### ISSUE TITLE
Page 76- Beat 12 mislabled beat 4; Refers to nonexistent combat

### ISSUE THREAD

**Issue by Imcoveredinbees** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#28]
In the sidebar of Mission 4, the beat "Patience, Patience" is mislabled beat 4 instead of beat 12. In addition, it refers to a non-existence combat in the same sidebar, Long Way Home

**Comment by KaiTave** [comment]
Also a minor point of clarification, page 76 refers to a combat encounter as "Roadblocked" while the encounter on page 80 is called "Roadblock."

**Comment by Piezoelectric** [comment]
Now has Beat 11, and Beat 12: "Patience, Patience", and Combat: Roadblock
