### ISSUE TITLE
183 - Mech Role Labeling Inconsistency

### ISSUE THREAD

**Issue by ghost** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#30]
The Sagarmatha includes a Striker icon along with its size, which is inconsistent with previous iterations of the frame (being previously labeled a Defender). In addition, it is the only alt frame that includes a role icon, the Enkidu, Genghis Mk I, and Ranger Swallowtail opting for a subtitle instead. It is unclear which formatting option is correct, as the Kidd also includes a role icon.

**Comment by Piezoelectric** [comment]
Icons have been added; however the Sagarmatha still doesn't include a role subtitle. New issue will be created.
