### ISSUE TITLE
Page 206 - Canopy "Linked" trait is labelled Discipline

### ISSUE THREAD

**Issue by Piezoelectric** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#33]
![image](https://user-images.githubusercontent.com/23746623/110879400-84d81a80-82a2-11eb-9524-30f2427fb7a5.png)
![image](https://user-images.githubusercontent.com/23746623/110879412-89043800-82a2-11eb-8089-6e8f4088d72e.png)

This should read "Linked trait"

**Comment by KaiTave** [comment]
More specifically it should read "Linked" instead of Discipline. Discipline is the name of another Eidolon layer's trait (the Punishment layer).
