### ISSUE TITLE
Page 51 - Venom HP

### ISSUE THREAD

**Issue by fighterchimp** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#34]
Venom, the Elite Strider, has 8 HP listed in their statblock, but the Strider stat block in the appendix has them at 10HP at Tier 1.

**Comment by fighterchimp** [comment]
Venom's statblock also has Evasion listed at 8, whereas Tier 1 Striders in the appendix are at 10.

**Comment by Piezoelectric** [comment]
Venom's HP is now 10, Evasion is now 10, matching the statblock on 192
