### ISSUE TITLE
Page 188 - Ranger Swallowtail Core Power Errata

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#35]
Per a discussion in New Release Feedback, the Ranger Swallowtail's core active power underwent an editing change that has had an unaccounted for knock-on effect. Guerrilla Warfare used to say this:

_"For the rest of the scene, when the swallowtail or any of its allies in its sensor range end their turn in a zone that grants soft cover, they become invisible. This invisibility breaks if they leave the zone, take damage, make an attack roll, force a save, take a reaction, or take any other hostile action that affects another character."_

It now says this:

_"Additionally, for the rest of the scene, allied characters within SENSORS gain the benefits of GROUNDED."_

The issue is that with this change, the effect no longer breaks on allies taking damage, which means that an entire party can remain invisible at the end of every one of their turns even after taking hostile actions.

Tom has been made aware of this and has stated that this was not intended and that this should be errataed.

Kai Tave, Killswitch Gremlin — Today at 6:07 PM
I think Sgt Briar's concern is that it breaks on hostile action yes, but then if you end your turn in the zone it just reapplies itself
So you shoot and lose invisible, but then you regain it at the end of your turn

findommed by Amazon — Today at 6:07 PM
ah yeah true
I'll probably add a rider in

findommed by Amazon — Today at 6:08 PM
or just revert it to break on dmg
it was an editing change

findommed by Amazon — Today at 6:08 PM
we'll errata that

Since space may be at a premium on that page, if the errata is to have the effect break on allies benefitting from it, one possible revision could be the following change to the sentence:

"Additionally, for the rest of the scene, allied characters within SENSORS gain the benefits of GROUNDED, **though this effect also breaks for them if they take damage as well."**

**Comment by Piezoelectric** [comment]
The 2021-05-17 release changes the wording of Grounding. The solution implemented is now that the allies *and* the Swallowtail Ranger lose Grounded on taking damage. See here: https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/154
