### ISSUE TITLE
Page 190 - Avenger's Revenge Trait shouldn't proc on Drones

### ISSUE THREAD

**Issue by Piezoelectric** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#37]
## Issue
The Avenger's *Revenge* Trait states it procs when "an allied non-Grunt character is destroyed". Word of Tom indicates that Revenge shouldn't proc on Drones, but "allied non-Grunt characters" includes Drones.

## Evidence

![image](https://user-images.githubusercontent.com/23746623/110889271-71817b00-82b3-11eb-892a-cdfc987bfcc0.png)

![image](https://user-images.githubusercontent.com/23746623/110889480-d0df8b00-82b3-11eb-9a24-2a72d5b23e7d.png)

## Resolution

Revenge should proc when an allied non-Grunt, non-Drone character is destroyed.

**Comment by KaiTave** [comment]
Understanding that space on the Avenger's page is at a premium for any additional words, the most space efficient way of incorporating this might be something along these lines:

"The Avenger's Revenge trait states "If an allied non-**GRUNT/DRONE** character is destroyed within RANGE 5, for the rest of the scene the Avenger gains OVERSHIELD 8/12/16, +5 base damage on its attacks, and +1 ACCURACY on all attacks, checks, and saves."

**Comment by KaiTave** [comment]
If changes are made to the base Avenger NPC statblocks, those changes may also need to be reflected in the text of [The Weapon] on page 81 as well, which is an Avenger NPC.

**Comment by Piezoelectric** [comment]
Change has been made to pg190 statblock

Pure Rage on page 81 has **not** been changed, still reading "allied non-Grunt"
