### ISSUE TITLE
Page 145 - Mission Summary Reward Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#38]
On the summary on page 145, it reads:

"There are also two pieces of EXOTIC GEAR
available. By defeating Beggar One,
characters can take the FRAGMENT OF
BEGGAR ONE , and going to the Cassander
allows characters to take and access the
WOLF -SPIDER DRONE ."

In much earlier drafts of Wallflower there was a piece of Exotic Gear associated with the Wolf-Spider fight aboard the Cassander, however that is not the case in this final version of the adventure. Instead the players gain a special Orbital Bombardment action they can call upon. The mission summary should probably be adjusted to reflect this, for example:

"There are also two rewards available. By going to the Cassander, players are able to unlock a powerful ORBITAL BOMBARDMENT ability, and defeating Beggar One allows characters to take the FRAGMENT OF BEGGAR ONE, a piece of EXOTIC GEAR."

**Comment by Piezoelectric** [comment]
> "There are also two rewards available. By going to the Cassander, players are able to unlock a powerful ORBITAL BOMBARDMENT ability, and defeating Beggar One allows characters to take the FRAGMENT OF BEGGAR ONE, a piece of EXOTIC GEAR."

This exact text is now used in the summary
