### ISSUE TITLE
Page 11 - Clarification needed - Number of combats per mission

### ISSUE THREAD

**Issue by Piezoelectric** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#39]
## Description

On page 11, No Room for a Wallflower recommends 2-3 fights per full repair, instead of the Core Book's recommendation of 3-4. 

Is this 
* a typo? 
* a change specific for the Wallflower campaign? 
* Or is this a broader shift in design philosophy (i.e. all missions should be 2-3 instead of 3-4)?

## Impact

It doesn't necessarily matter in terms of balance, but it's a big shift in community wisdom/tribal knowledge, since a lot of people have internalized "core book says 3-4". When people come to #gm-corner asking "hey how many fights do I put per mission", it would be nice to have a consistent answer.

## Evidence

![image](https://user-images.githubusercontent.com/23746623/110963026-35800180-8317-11eb-9984-57a5185da09a.png)
**Wallflower, Page 11**

![image](https://user-images.githubusercontent.com/23746623/110965634-fd2df280-8319-11eb-963a-dfe189cad673.png)
**Core Book, Page 264**

**Comment by unrelevant-user-name** [comment]
Tom confirmed during that 200th Interpoint mission that it's an intentional shift in philosophy.

**Comment by Piezoelectric** [comment]
@unrelevant-user-name  do you have a timestamp on that? I believe you, I just don't want to comb through the whole VOD myself

**Comment by unrelevant-user-name** [comment]
5:34:13

**Comment by Piezoelectric** [comment]
Ralf pointed out that Wallflower adjusted the number of combats from 3-4 to 2-3.
Tom: "Yes, [Wallflower] did...it was a conscious decision, it was more realistic, I think, for [how] people typically play".
