### ISSUE TITLE
Page 105 - Extraction or Escort Sitrep?

### ISSUE THREAD

**Issue by ninjaxenomorph** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#40]
The "Slap in the Face" combat says it is to be run with a (modified) Extraction sitrep, but the narrative and description closer fits an Escort sitrep, since the players start with control over the ag-drones.

**Comment by Piezoelectric** [comment]
Sidebar now reads "Sitrep: Escort". The details also read "The PCs must escort the ag-drone to the EZ and extract it by the end..."
