### ISSUE TITLE
Page 146, 167 - Consumption Clock Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#42]
On page 146, the campaign introduces the Consumption Clock leading up to the Beggar One fight. It instructs GMs to make a clock with 3 segments, 4 if the players destroyed Patience earlier before B1 can consume them. However, on page 167, it says the following:

"If the PCs encounter Beggar One before its **four-
segment** Consumption clock has been completed (**or
the five-segment version, if the PCs killed Patience**
during BEAT 16A.6 MOUNTAINFALL ),"

In other words, one section says the clock should be 3-4 segments, the other describes it as 4-5. Because the clock is illustrated on page 145 as being a 3 segment clock, I am assuming that page 146 is correct and that 3-4 segments is the intended length, which means the passage on 167 is in error and should be corrected as such:

"If the PCs encounter Beggar One before its **three-
segment** Consumption clock has been completed (**or
the four-segment version, if the PCs killed Patience**
during BEAT 16A.6 MOUNTAINFALL ),"

**Comment by Piezoelectric** [comment]
Page 167 now reads 

> "If the PCs encounter Beggar One before its three-
segment Consumption clock has been completed (or
the four-segment version, if the PCs killed Patience
during BEAT 16A.6 MOUNTAINFALL ),"
