### ISSUE TITLE
Page 105 - Slap In The Face Typo

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#43]
In the summary box for the Slap In The Face mission on page 105, it lists "**3x** ag-drone (Size 1, 10 HP)." As there's only a single ag-drone for the players to escort, this should instead be "**1x** ag-drone (Size 1, 10 HP)"

**Comment by Piezoelectric** [comment]
this is fixed
