### ISSUE TITLE
190-193 & 199-209 - NPC Weapon Format Inconsistency

### ISSUE THREAD

**Issue by ghost** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#49]
The Avenger, Lurker, Strider, and Eidolon weapons suffer from inconsistent formatting. 

1. Some weapons lack the flat to-hit value, even when it should be +0:
Ranger Long Rifle, Explosive Rifle
Based on the Core Rulebook Cataphract Ram Cannon, for weapons with Accuracy/Difficulty but a +0 flat to hit, the format for these weapons should be +0, +1�
- This issue extends to Psalm's strider, Venom - Page 51.

2. The label "vs evasion" or "vs Evasion" is not found in core, and is probably a holdover from draft material. It should be removed from the following weapons: 
Slug Pistol, Judgement Shotgun, Scouring Whip, Ripper Claws, Shoulder Mortar, Mag Shotgun.
- These issues extend to the variants with embedded stablocks: Venom - Page 51, [The Weapon] - Page 81, [The End] - Page 101.

3. Like with certain standard NPCs, Eidolon Memetic weapons also list 'vs Evasion' and 'vs E-Defense' tags, although here it is unclear whether it is a formatting issue or not. The Memetic weapon category does not specify whether it tracks Evasion or E-Defense by default, although it is assumed that it inherits the property of all weapons to target Evasion by default. Where 'vs E-Defense' is used, it should be replaced with 'Smart'.

**Comment by Piezoelectric** [comment]
The NPC statblocks were addressed in https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/109

Venom's statblock now lists +0 / +1 accuracy

The Weapon's statblock lists +0 / +1 difficulty, and +2 

The End's statblock now lists +0

Certain eidolon weapons are listed as Smart, with the remainder assumed to target evasion. (Example: Truth Spear, Keening Wail)
