### ISSUE TITLE
Page 194 - Spite NPC Size Icon Error

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#5]
The Spite NPC through most of its iterations has been size 2 rather than size 1. It's possible that this change was intended on the backend, but I would confirm with Tom that this is the intended case rather than an error.

e; on further evaluation, the Spite's own statblock lists it as Size 2 as well. With that in mind, I'm inclined to think that the icon is simply in error rather than this being a last minute change.

**Comment by Piezoelectric** [comment]
Statblocks list size 2, as previously. The icon is now the size 2 icon, as intended.
