### ISSUE TITLE
44-45 Patience Misgendered

### ISSUE THREAD

**Issue by ghost** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#50]
Patience is referred to several times with 'his'.
On the attack: "Patience sighs and spins a projected pen on _his_ desk."
On tracking the raiders: "Patience stands from _his_ desk and waves an image up onto an otherwise blank wall of _his_ office."
Instances should be replaced with **their**.

**Comment by Piezoelectric** [comment]
Both sentences mentioned here have been corrected.
