### ISSUE TITLE
Page 121 - Word Choice - Cultural Sensitivity 

### ISSUE THREAD

**Issue by unrelevant-user-name** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#51]
The word "worship" is used in reference to a saint, but in Christianity worship is reserved for God alone, so the appropriate word here would be "veneration." I feel self-conscious submitting this, even though I'm not even Catholic, but accusations of saint worship having a long history in internecine conflict, and I feel this is in-line with Lancer's spirit of cultural sensitivity.

**Comment by Piezoelectric** [comment]
The text now reads "The **veneration** of St. Tellus continues to thrive among the Union Catholics of Hercynia..."
