### ISSUE TITLE
81 - [The Weapon] Role Inconsistency

### ISSUE THREAD

**Issue by ghost** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#53]
[The Weapon] is an Avenger NPC, which is labeled under the NPC section as a Striker/Defender. However, under [The Weapon]'s description, it is labeled exclusively as a Striker, and includes only a Striker Icon, when it should include both Striker and Defender icons, based on Venom's inclusion of both of its role icons on Page 51.

**Comment by Piezoelectric** [comment]
Now includes both roles in the subtitle, and both icons in the upper-right corner
