### ISSUE TITLE
Page 102 - Through The Closed Door Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#57]
In the mission Through The Closed Door, it mentions "The reinforcements arrive at the end of the second round." However, reinforcement units are not listed in the mission unit summary. In an earlier draft of the campaign, this mission listed the following units as reinforcements:

REINFORCEMENTS
– 1x SCOUT (Weakness Analyzer)
– 1x ACE (Bombing Bay, Chaff Launchers)

So either this is an omission, or the mission was adjusted to not have reinforcements anymore. If the former, then reinforcements should be listed in the unit summary. If the latter, then the sentence mentioning reinforcements should be removed.

**Comment by Piezoelectric** [comment]
Reinforcements (Scout and Ace) have been added. The reinforcements arrive clause has been left under Details.
