### ISSUE TITLE
Page 26 - Overland/Kingwatcher is erroneously referred to as Overland/Kingmaker

### ISSUE THREAD

**Issue by spaldr** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#58]
In the section for Beggar One on page 26 O/K is mistakenly referred to as Overland/Kingmaker

**Comment by Piezoelectric** [comment]
Text changed and now reads
![image](https://user-images.githubusercontent.com/23746623/118576025-57e62f00-b74d-11eb-911a-624bce5818fd.png)
