### ISSUE TITLE
Page 167: Eidolon Layer Name Discrepancy

### ISSUE THREAD

**Issue by EsotericOdyssey** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#59]
for the extra eidolon layers listed if B1 fills up the consumption clock, it gives "Adamantine" as layer 4, when that layer is just named "Adamant" in the eidolon section in the appendix

**Comment by KaiTave** [comment]
https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/13

**Comment by Piezoelectric** [comment]
Closing as duplicate
