### ISSUE TITLE
HUC Raid Timeframe contradiction (page 24-page 44)

### ISSUE THREAD

**Issue by Eldraen** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#62]
The time at which the raids have started on Evergreen aren't consistent across a few places in the book, the overview of the situation on **page 24** mentions that the attacks started in 5012u-5013u (compared to the campaign present of 5014u) while Patience mentions that they started a month ago on **page 44**, it is unclear which is right currently.

**Comment by Piezoelectric** [comment]
Page 24: That changed following a series of attacks that took place from 5012 to 5013u, executed by unidentified but well-armed assailants.

Page 44: ON THE ATTACKS
“The attacks began fourteen months ago..."
