### ISSUE TITLE
Page 92 - Narration text should be italicized

### ISSUE THREAD

**Issue by junbl** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#63]
The top two paragraphs of the second column on page 92 are written as narration (in second person), continuing from the first column, but are not italicized or indented like the rest of the narrative text in each beat.

**Comment by Piezoelectric** [comment]
The narrative text is now stylized properly

![image](https://user-images.githubusercontent.com/23746623/118552904-31140280-b725-11eb-8190-91c1ddcede48.png)
