### ISSUE TITLE
Page 101 - Inconsistent capitalization in [The End]'s statblock

### ISSUE THREAD

**Issue by junbl** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#64]
[The Weapon], [The Broadcast], and [The Accumulation] are all consistently referred to with "The" capitalized. The statblock for [The End], however, uses lowercase "the" in its description and in the Umbral Shroud and Mission Creep traits, but capitalized in other traits and in the sitrep on p 100.

**Comment by Piezoelectric** [comment]
All text on pg 101 now refers to The End
