### ISSUE TITLE
Page 101 & 191 - Lurker systems use Burst when Blast may be intended

### ISSUE THREAD

**Issue by LogistyxCat** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#65]
The descriptions for the Umbral Shroud and Empower Shroud (Mission Creep on pg. 101) systems list an area of Burst type. As defined in the core rulebook, Burst areas should be centered on the acting character.

As the Umbral Shroud system creates an area defined "in a free [burst] 1 area in range 5", it may be better to use the Blast symbol for clarification. For consistency, Empower Shroud/Mission Creep description should also be updated unless the intent is to center the zone on the Lurker NPC's position on use (in which case this point may need to be clarified).

**Comment by Piezoelectric** [comment]
101 
* umbral shroud uses blast icon
* mission creep uses blast icon

191
* umbral shroud uses blast icon
* empower shroud uses blast icon
