### ISSUE TITLE
Page 26 - Typo - "and one it thought it may be able"

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#66]
Should this be "thought it might have been able to"?

**Comment by KaiTave** [comment]
The whole sentence is "Beggar One was the manifestation of O/K’s “ideal” form and one it thought it may be able to save itself with," it's structured correctly and doesn't need changing.

**Comment by KaiTave** [comment]
"Beggar One was the manifestation of O/K’s “ideal” form and one it thought it may be able to save itself with"

The whole sentence seems to be grammatically and structurally correct, so I don't think it needs to be changed.

**Comment by The-Trilobite** [comment]
Got it. That felt like a possible tense change to me, so I figured it'd be better to check just in case.

**Comment by The-Trilobite** [comment]
Possible tense conflict addressed by Kai.
