### ISSUE TITLE
Page 70 - Typo - "can full repair"

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#70]
Possibly "can make a full repair"?

**Comment by KaiTave** [comment]
Within the confines of Lancer, saying that players "can full repair" is also acceptable sentence structure, and not necessarily indicative of a typo or missing words.

**Comment by The-Trilobite** [comment]
Got it. Thank you! It seemed like it was possibly correct, but hopefully making sure like this is the right thing to do?

**Comment by The-Trilobite** [comment]
Possible verb issue addressed by Kai
