### ISSUE TITLE
Page 79 - Possible word choice error - "out of convenience more than anything."

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#71]
Should this be "more than anything else?" "More than anything" often means a very strong longing or desire for something.

**Comment by KaiTave** [comment]
The term used in this way is commonly acceptable sentence construction, and I do not believe it constitutes a typo.

**Comment by The-Trilobite** [comment]
Makes sense to me! In cases like this, should I close the ticket, or is that something that happens later or is done by someone else?

**Comment by The-Trilobite** [comment]
Possible phrase definition problem, addressed by Kai.
