### ISSUE TITLE
Page 118 - Possible word choice error - "they realize the surface-dwellers are much alike"

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#73]
Should this be "they realize _they and_ the surface dwellers are much alike"?

**Comment by Piezoelectric** [comment]
Text now reads

![image](https://user-images.githubusercontent.com/23746623/118552414-8c91c080-b724-11eb-8a57-ff9d7ef79637.png)
