### ISSUE TITLE
Page 148 - Typo - ""Brava, some trust militia troopers"

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#79]
Maybe "trusted" or "trustworthy"?

**Comment by Piezoelectric** [comment]
Text now reads "trusty militia troopers":

![image](https://user-images.githubusercontent.com/23746623/118552061-0e351e80-b724-11eb-905d-00dd5d2e4bbc.png)
