### ISSUE TITLE
Page 190 - Avenger Revenge Clarification

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#8]
The wording for the Avenger NPC's Revenge trait states:

"for the rest of the scene the Avenger gains OVERSHIELD 8/12/16, **+5 base damage on its attacks**, and +1 Accuracy on all attacks, checks, and saves."

Currently this wording means that the Avenger can be read as dealing 5 damage with tech attacks such as the default NPC Invasion, which I'm reasonably confident is not intended. Depending on whether Revenge is meant to work with Ram, Grapple, and Improvised Attacks, the wording for this should be either "+5 base damage on ranged and melee attacks" (which would include those) or "+5 base damage on weapon attacks" (which would not). Tom will likely need to weigh in to determine the precise wording which he wishes to use.

**Comment by KaiTave** [comment]
The Avenger's page has very little free space for additional wording changes in general, and given that this ticket https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/37 is known errata that needs to be incorporated, if additional clarification is necessary regarding which attacks the Avenger gains damage to, then careful conservation of space may be necessary.

If the worst absolutely comes to pass, the Tactics section for the Avenger could potentially be edited to clear up a line's worth of room or so. For example:

"Avengers become much more threatening when their allies start falling around them. Place them near high-priority targets to take advantage of their REVENGE ability, forcing characters to choose between taking them out first or suffering more for destroying their allies."

**Comment by KaiTave** [comment]
If changes are made to the base Avenger NPC statblocks, those changes may also need to be reflected in the text of [The Weapon] on page 81 as well, which is an Avenger NPC.

**Comment by Piezoelectric** [comment]
@KaiTave The wording currently reads "ranged and melee attacks", which RAW includes Grapples, Rams. Still not clear if this is intended.  From the RTF file, there's this line:

> Avenger’s revenge trait should read +5 base damage to its ranged and melee attacks, not intended to work with tech attacks

I'll leave it up to you to decide if this requires further review

**Comment by KaiTave** [comment]
I think it's probably fine at this point, I doubt it's going to be refined further at this stage.
