### ISSUE TITLE
Page 67: REGRET Self-Destructs

### ISSUE THREAD

**Issue by Arcranmon** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#81]
In the 'If REGRET is not defeated', it says that REGRET self-destructs. The 'self-destructs' uses the bolded font usually used for abilities, but self-destruct isn't an NPC action. Some clarification as to whether REGRET should use the player's self-destruct option, or if this is just a way to end the encounter in a flavorful way would be helpful.

**Comment by Piezoelectric** [comment]
Text now mentions player self-destruct rules:

![image](https://user-images.githubusercontent.com/23746623/118551876-d201be00-b723-11eb-87c2-48d55670ced0.png)
