### ISSUE TITLE
Page 160 - Tense mismatch - 4th paragraph narration

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#84]
In the fourth paragraph, where Beggar One speaks to the PCs, we begin with one tense (The voice pushes...it says...) and then switch to another tense (Tired, it continued.) It may be desirable to put this in the present, which I believe matches the rest of the narration?

**Comment by Piezoelectric** [comment]
Text now reads 

> Tired, it continues. “Pursuant to Union strategic directives, I will utilize every resource at my disposal to break you.”
> A shape descends into view ...
> Silhouette analysis comes back...
