### ISSUE TITLE
Page 170 - Possible word choice error - "ON THE FRONTLINES"

### ISSUE THREAD

**Issue by The-Trilobite** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#86]
Perhaps "FRONT LINES"? "Frontline" is usually an adjective, and "front line" is commonly used to denote the position.

**Comment by Piezoelectric** [comment]
Text now reads

![image](https://user-images.githubusercontent.com/23746623/118551292-628bce80-b723-11eb-9612-8752a75c36c6.png)
