### ISSUE TITLE
Page 203 - Rancourous Layer 'Skill Tests'

### ISSUE THREAD

**Issue by Namoeleon** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#87]
On page 203, in the description of the Rancourous Eidolon layer's abilities 'FURY' and 'GRIEF', the book calls for a Hull 'test' and Engineering 'test', respectively. I couldn't find any mention of such a mechanic in the Core Book or Wallflower itself, so I assume that it's supposed to refer to a check or save, instead.

**Comment by KaiTave** [comment]
Given that other Eidolon abilities call for saves, I assume that these should be a Hull save and an Engineering save respectively.

**Comment by Piezoelectric** [comment]
Text amended to Hull save, Engineering save
