### ISSUE TITLE
Page 200 - TYPO - Blurred Layer Infinite Blur discrepancy

### ISSUE THREAD

**Issue by Icosacube** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#9]
On page 200, the Blurred Eidolon's Infinite Blur trait states that characters effected by it can "Dash 1/turn as a free action", when presumably it's supposed to be "Boost 1/turn".

**Comment by Piezoelectric** [comment]
Now reads "Boost 1/turn as a free action"
