### ISSUE TITLE
Page 127 - Typo - Ecdysis instead of ecdyses

### ISSUE THREAD

**Issue by junbl** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#90]
In the second paragraph on page 127, the fourth sentence (beginning "Endeavor's integuments...") ends "their many ecdysis," which should probably be "their many ecdyses." Fun word!

**Comment by KaiTave** [comment]
Confirming that its use in this sentence ("charting their many ecdysis") should be **ecdyses** which is the plural form of ecdysis.

**Comment by junbl** [comment]
Yeah you got it. Sorry if I was unclear!

**Comment by Piezoelectric** [comment]
Text amended to "ecdyses"
