### ISSUE TITLE
Page 160 - Typo 2D6 vs 2d6

### ISSUE THREAD

**Issue by lenaleciel** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#91]
In the description of the decaying power cores, the damage they deal when destroyed is listed as 2D6, with a small capital D, while all other instances of Xd6 in describing damage rolls is listed as Xd6, with a lowercase d.

**Comment by Piezoelectric** [comment]
The text now reads

![image](https://user-images.githubusercontent.com/23746623/118550759-afbb7080-b722-11eb-8a7e-55645bad3d6c.png)

Curiously the related issue on page 133 / this issue wasn't fixed: https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/115
