### ISSUE TITLE
Pages 190-194: NPC Class Role Icon Discrepancy

### ISSUE THREAD

**Issue by KaiTave** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#94]
The NPC classes on pages 190-194 have size icons on both the upper left and upper right of their pages. Per the formatting of the Lancer core rulebook, for consistency they should have the size icon on the upper left but the upper right should be the corresponding role icons for each NPC class (Striker/Defender for the Avenger, Striker for the Lurker, Artillery/Striker for the Strider, and Defender for the Spite).

**Comment by Piezoelectric** [comment]
Icons have been amended
