### ISSUE TITLE
Page 145: Wolf-Spider Drone

### ISSUE THREAD

**Issue by Arcranmon** [RancidRance/Wallflower-Part-1-Release-Typos-and-Errors#96]
Page 145 lists the Wolf-Spider Drone as a piece of Exotic Gear that the party can recover, but the results of the 'Sins of the Father' combat (where the original Wolf-Spider Drone is fought) do not list any exotic gear the party can collect. As far as I can tell, the Wolf-Spider Drone is never listed as exotic gear.

**Comment by KaiTave** [comment]
This discrepancy has already been noted: https://github.com/RancidRance/Wallflower-Part-1-Release-Typos-and-Errors/issues/38

**Comment by Piezoelectric** [comment]
Closed as duplicate
